'use client';
import {Plus,Trash2,RotateCcw} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import {Field,Notice,Select} from './wizard-ui';
import * as F from '@/lib/framework.mjs';
export function Gaps({s,change}){const gaps=F.gapsFor(s);function edit(id,key,value){change(p=>id.startsWith('custom-')?{...p,customGaps:p.customGaps.map(g=>g.id===id?{...g,[key]:value}:g)}:{...p,gapEdits:{...p.gapEdits,[id]:{...p.gapEdits[id],[key]:value}}},3)}return <><div className="section-top"><span className="pill">{gaps.length} gargalos no plano</span><Button variant="outline" onClick={()=>change(p=>({...p,customGaps:[...p.customGaps,{id:'custom-'+crypto.randomUUID(),title:'Novo gargalo',action:'',track:'Técnica',impact:2,effort:2,risk:2,owner:''}]}),3)}><Plus/> Adicionar</Button></div><p className="muted">Dimensões baixas e médias viram sugestões. Impacto, esforço e risco começam em 2; revise essas estimativas.</p>{!gaps.length&&<Notice>Nenhum gargalo listado. Você pode adicionar bloqueios observados pelo time.</Notice>}{gaps.map(g=><div className="gap-card" key={g.id}><div className="gap-head"><span className={'priority '+(F.priority(g)>=11?'critical':'')}>{F.priority(g)}/21 · {F.priority(g)>=11?'Crítico':'Médio'}</span><span className="muted">+{g.effort===1?30:g.effort===2?90:180} dias</span><Button variant="ghost" size="icon" aria-label={'Remover '+g.title} onClick={()=>change(p=>({...p,removedGaps:[...p.removedGaps,g.id]}),3)}><Trash2/></Button></div><Field label="Gargalo"><Input value={g.title} onChange={e=>edit(g.id,'title',e.target.value)}/></Field><Field label="Ação para remover o bloqueio"><Textarea value={g.action} onChange={e=>edit(g.id,'action',e.target.value)}/></Field><div className="three-fields">{[['impact','Impacto'],['effort','Esforço'],['risk','Risco se não agir']].map(([key,label])=><Field label={label} key={key}><Select label={label+' de '+g.title} value={g[key]} onChange={v=>edit(g.id,key,Number(v))} options={[[1,'Baixo'],[2,'Médio'],[3,'Alto']]}/></Field>)}</div><div className="two-fields"><Field label="Trilha"><Select label={'Trilha de '+g.title} value={g.track} onChange={v=>edit(g.id,'track',v)} options={['Técnica','Organizacional','Cultura']}/></Field><Field label="Responsável"><Input placeholder="A definir" value={g.owner} onChange={e=>edit(g.id,'owner',e.target.value)}/></Field></div></div>)}{s.removedGaps.length>0&&<Button variant="outline" onClick={()=>change(p=>({...p,removedGaps:[]}),3)}><RotateCcw/> Restaurar removidos</Button>}<details><summary>Como funciona a priorização?</summary><p>Impacto × 3 + (4 − esforço) × 2 + risco × 2. Cada valor vai de 1 a 3; crítico ≥ 11.</p><p>O máximo calculado é 21. O texto do PDF informa 15; esta adaptação preserva a fórmula e o limiar. Marcos sugeridos por esforço: baixo +30d, médio +90d, alto +180d. Ajuste a execução conforme as dependências.</p></details></>}
export function Adoption({s,change,nav}){const diag=F.diagnostic(s.answers),stages=F.stagePlan(s);return <><div className="section-top"><span className="pill">{diag?F.templateFor(s.context.usage,diag.level):'Diagnóstico pendente'}</span><span className="muted">6 estágios do SDLC</span></div><Notice>O nível recomendado combina seu alvo com os limites do diagnóstico e a proficiência. Informar um nível desejado não declara que ele já foi atingido.</Notice>{!diag&&<Button onClick={()=>nav(0)}>Responder diagnóstico</Button>}{stages.map((st,i)=><div className="stage-card" key={st.key}><div className="stage-head"><h3><span>0{i+1}</span>{st.name}</h3><span className="pill">{F.levelLabels[st.recommended]}</span></div><div className="two-fields"><Field label="Nível desejado"><Select label={'Nível desejado para '+st.name} value={st.desired} onChange={v=>change(p=>({...p,targets:{...p.targets,[st.key]:Number(v)}}),4)} options={F.levelLabels.map((l,i)=>[i,l])}/></Field><Field label="Pessoas em L2+ neste estágio (%)"><Input aria-label={'Percentual L2+ em '+st.name} placeholder="0" type="number" min={0} max={100} step={1} value={s.l2[st.key]??''} onChange={e=>{const v=e.target.value;if(v===''||(/^\d{1,3}$/.test(v)&&Number(v)<=100))change(p=>({...p,l2:{...p.l2,[st.key]:v}}),4)}}/></Field></div>{st.desired>st.recommended&&<Notice tone="warning">{st.reasons.join(' ')}</Notice>}<div className="responsibilities"><p><b>IA propõe</b>{st.ai}</p><p><b>Humano decide</b>{st.human}</p></div><details><summary>Critérios de avanço e o que evitar</summary><ul>{st.criteria.map(x=><li key={x}>{x}</li>)}</ul><p><b>Evite:</b> {st.anti}</p></details></div>)}<p className="source-note">Templates e calibrações: guia, pp. 21–25. A matriz inicial de níveis é uma proposta desta adaptação, editável acima. Em conflitos, Conservador tem precedência.</p></>}
