'use client';
import {useEffect,useLayoutEffect,useRef,useState} from 'react';
import {flushSync} from 'react-dom';
import {ArrowRight,ArrowLeft,ArrowUpRight,Check,Layers3,Download,Upload,RotateCcw,Info,FileText,LogOut} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Progress} from '@/components/ui/progress';
import {AlertDialog,AlertDialogTrigger,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from '@/components/ui/alert-dialog';
import {download} from '@/components/wizard-ui';
import Diagnostic from '@/components/diagnostic';
import {Enablers,Pilot} from '@/components/people-phases';
import {Gaps,Adoption} from '@/components/adoption-phases';
import Governance from '@/components/governance-phase';
import Scale from '@/components/scale-phase';
import PlanReport from '@/components/plan-report';
import * as F from '@/lib/framework.mjs';
import {validateSaved} from '@/lib/saved.mjs';
import {SourceNotes} from '@/components/modernization';
import {draftStorageKey,readDraft} from '@/lib/browser-storage.mjs';
const subtitles=['Conheça seu ponto de partida','Defina quem conduz a jornada','Prepare um experimento real','Remova os bloqueios certos','Evolua cada etapa do SDLC','Transforme regras em prática','Expanda com evidências'];
const titles=['Toda jornada começa com um ponto de partida.','Quem vai conduzir a mudança?','Comece onde é possível aprender.','Destrave o caminho para a adoção.','IA no fluxo. Uma etapa de cada vez.','Confiança também se constrói.','Escale o que já demonstrou valor.'];
const descriptions=['Entenda a prontidão da sua engenharia e descubra onde agir primeiro.','Dê à iniciativa um responsável, patrocínio e espaço para aprender.','Escolha um time com autonomia e uma hipótese que você possa medir.','Priorize ações por impacto, esforço e risco. Ajuste as sugestões ao seu contexto.','Defina níveis de adoção, responsabilidades e critérios para avançar.','Acompanhe a implementação das políticas, padrões e controles do framework.','Planeje as ondas e acompanhe a mudança com métricas de adoção e impacto.'];
export default function Home({viewer,canMigrateLegacy=false}){
 const KEY=draftStorageKey(viewer.id);
 const [s,setS]=useState(F.initialState),[loaded,setLoaded]=useState(false),[saved,setSaved]=useState(false),[saveBlocked,setSaveBlocked]=useState(false),[errors,setErrors]=useState([]),[message,setMessage]=useState(''),[report,setReport]=useState(false),[method,setMethod]=useState(false),[reset,setReset]=useState(false);const file=useRef(null),heading=useRef(null),contentScroll=useRef(null),methodology=useRef(null),errorBox=useRef(null),stateRef=useRef(s);stateRef.current=s;
 useLayoutEffect(()=>{
  if(report)return;
  const pane=contentScroll.current;
  const form=pane?.querySelector('.work-grid');
  const main=pane?.querySelector('main');
  if(!form||!main)return;
  // Keep the card at the form's unscrolled top, including wrapped headings.
  const align=()=>{
   const top=form.getBoundingClientRect().top+pane.scrollTop;
   pane.style.setProperty('--context-top',`${top}px`);
  };
  align();
  const observer=new ResizeObserver(align);
  observer.observe(main);
  observer.observe(pane);
  return ()=>observer.disconnect();
 },[report,s.step,message]);
 useEffect(()=>{try{const raw=readDraft(localStorage,viewer.id,canMigrateLegacy);if(raw){const original=JSON.parse(raw);setS(validateSaved(original));if(original.schema===1)setMessage('Seu plano foi recuperado na v2. Revise o contexto, o piloto e os controles atualizados. O rascunho original da v1 permanece guardado neste navegador.')}}catch{setSaveBlocked(true);setMessage('Não foi possível recuperar o rascunho. O original foi preservado. Importe um backup ou use Reiniciar para criar um novo plano.')}setLoaded(true)},[]);
 useEffect(()=>{if(!loaded||saveBlocked)return;try{localStorage.setItem(KEY,JSON.stringify(s));setSaved(true)}catch{setSaved(false)}},[s,loaded,saveBlocked]);
 useEffect(()=>{contentScroll.current?.scrollTo({top:0});heading.current?.focus({preventScroll:true});setErrors([])},[s.step,s.q,report]);
 useEffect(()=>{if(errors.length){errorBox.current?.focus({preventScroll:true});errorBox.current?.scrollIntoView({block:'nearest'});}},[errors]);
 useEffect(()=>{if(method){methodology.current?.scrollIntoView({block:'start'});methodology.current?.focus({preventScroll:true});}},[method]);
 const change=(fn,phase=s.step)=>setS(prev=>{const next=fn(prev);return {...next,reviewed:prev.reviewed.map((v,i)=>i<phase?v:false)}});
 const group=(name,key,value,phase=s.step)=>change(p=>({...p,[name]:{...p[name],[key]:value},...(name==='pilot'||name==='context'?{v2:{...p.v2,experiment:{...p.v2.experiment,decision:'pending',decisionEvidence:''}}}:{})}),phase);
 const nav=(step)=>{setReport(false);setS(p=>({...p,step}));contentScroll.current?.scrollTo({top:0})};
 const diag=F.diagnostic(s.answers),done=s.reviewed.filter(Boolean).length;
 useEffect(()=>{const ctx=document.modelContext;if(!ctx?.registerTool)return;const controller=new AbortController();const defs=[{name:'read_adoption_plan',title:'Ler plano de adoção',description:'Lê o rascunho e diagnóstico autodeclarado do wizard, sem alterar o plano.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute(input){if(input&&Object.keys(input).length)throw new Error('Sem parâmetros.');const v=stateRef.current;return {state:v,diagnostic:F.diagnostic(v.answers),gates:F.executionGates(v)}}},{name:'stage_diagnostic_answers',title:'Preencher diagnóstico',description:'Preenche respostas de 1 a 3 das nove dimensões. Atualiza o rascunho visível, abre o diagnóstico e invalida revisões posteriores; não conclui fases nem comprova adoção.',inputSchema:{type:'object',properties:{answers:{type:'object',properties:Object.fromEntries(F.dimensions.map(d=>[d.key,{type:'integer',enum:[1,2,3]}])),additionalProperties:false,minProperties:1}},required:['answers'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){if(!input||Object.keys(input).some(k=>k!=='answers')||!input.answers||typeof input.answers!=='object'||!Object.keys(input.answers).length||Object.entries(input.answers).some(([k,v])=>!F.dimensions.some(d=>d.key===k)||![1,2,3].includes(v)))throw new Error('Use dimensões válidas com valores 1, 2 ou 3.');const next={...stateRef.current,answers:{...stateRef.current.answers,...input.answers},reviewed:Array(7).fill(false),bottleneck:'',step:0,q:0};if(F.diagnostic(next.answers))next.q=9;flushSync(()=>{setS(next);setReport(false)});return {status:'rascunho atualizado',diagnostic:F.diagnostic(next.answers)}}}];for(const tool of defs){try{Promise.resolve(ctx.registerTool(tool,{signal:controller.signal})).catch(()=>{})}catch{}}return()=>controller.abort()},[]);
 function advance(){if(s.step===0&&s.q<9){if(s.q===-1){if(!s.context.name.trim()||!Number.isInteger(Number(s.context.size))||Number(s.context.size)<1){setErrors(['Informe o nome e um tamanho inteiro válido para a engenharia.']);return}}else if(!s.answers[F.dimensions[s.q].key]){setErrors(['Selecione a alternativa mais próxima da realidade do time.']);return}setS(p=>({...p,q:p.q+1}));return}const errs=F.phaseErrors(s,s.step);if(errs.length){setErrors(errs);return}if(s.step===6){const missing=s.reviewed.findIndex((x,i)=>i<6&&!x);if(missing!==-1){setErrors([`Revise e confirme a fase ${missing+1} (${F.phaseNames[missing]}) antes de finalizar o plano.`]);return}}setS(p=>({...p,reviewed:p.reviewed.map((v,i)=>i===p.step?true:v),step:Math.min(6,p.step+1)}));if(s.step===6)setReport(true)}
 async function importFile(e){const selected=e.target.files?.[0];e.target.value='';if(!selected)return;try{if(selected.size>2000000)throw new Error('Use um arquivo JSON menor que 2 MB.');const next=validateSaved(JSON.parse(await selected.text()));if(!window.confirm('Substituir o rascunho atual pelo arquivo selecionado?'))return;setS(next);setSaveBlocked(false);setReport(false);setMessage(next.v2.migratedFrom==='v1'?'Plano importado e atualizado para a v2. Os novos critérios precisam de revisão.':'Rascunho v2 importado com sucesso.')}catch(err){setMessage(err.message||'Não foi possível importar o arquivo.')}}
 const props={s,setS,group,change,nav};
 return <div className="app-shell"><aside className="sidebar"><div className="brand"><div className="product-name">Bússola<span>ADOÇÃO DE IA</span></div></div><div className="side-label">SUA JORNADA</div><nav aria-label="Fases do framework">{F.phaseNames.map((p,i)=><button className={'phase '+(i===s.step&&!report?'active':'')} key={p} aria-current={i===s.step&&!report?'step':undefined} onClick={()=>nav(i)}><span className="step-number">{s.reviewed[i]?<Check size={13}/>:i+1}</span><div>{p}<small>{s.reviewed[i]?'Planejamento revisado':subtitles[i]}</small></div></button>)}</nav><div className="side-progress"><div><span>Planejamento</span><span>{done}/7</span></div><Progress value={done/7*100} aria-label="Fases do planejamento revisadas"/></div><button className={'phase report-link '+(report?'active':'')} onClick={()=>setReport(true)}><FileText size={17}/><div>Meu plano<small>Resumo e exportação</small></div></button><div className="side-bottom"><Layers3 size={19}/><p>Da intenção à prática.<small>Uma etapa de cada vez.</small></p></div></aside><div className="workspace"><header className="topbar">
 <div className="topbar-brand"><div className="topbar-title"><b>Bússola</b><span className="topbar-description"> / Framework de Adoção de IA</span> <span className="version">V2 · 2026</span></div><span className="save-status"><Check size={12}/><span>{!loaded?'Recuperando rascunho…':saved?'Salvo nesta conta e navegador':'Não salvo · exporte um backup'}</span></span></div>
 <nav className="topbar-actions" aria-label="Ações do planejamento">
  <Button variant="ghost" size="xs" title="Meu plano" aria-label="Meu plano" onClick={()=>setReport(true)}><FileText/><span className="action-label">Meu plano</span></Button>
  <Button variant="ghost" size="xs" title="Metodologia" aria-label="Metodologia" aria-expanded={method} aria-controls="methodology" onClick={()=>setMethod(!method)}><Info/><span className="action-label">Metodologia</span></Button>
  <Button variant="ghost" size="xs" title="Salvar backup" aria-label="Salvar backup" onClick={()=>download('bussola-v2-rascunho.json',JSON.stringify(s,null,2),'application/json')}><Download/><span className="action-label">Salvar backup</span></Button>
  <Button variant="ghost" size="xs" title="Importar" aria-label="Importar" onClick={()=>file.current?.click()}><Upload/><span className="action-label">Importar</span></Button>
  <AlertDialog open={reset} onOpenChange={setReset}>
   <AlertDialogTrigger render={<Button variant="ghost" size="xs" title="Reiniciar" aria-label="Reiniciar"/>}><RotateCcw/><span className="action-label">Reiniciar</span></AlertDialogTrigger>
   <AlertDialogContent className="reset-dialog"><AlertDialogHeader><AlertDialogTitle>Reiniciar o planejamento?</AlertDialogTitle><AlertDialogDescription>O rascunho deste navegador será apagado. Exporte um backup antes, se quiser preservar suas respostas.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Cancelar</AlertDialogCancel><AlertDialogAction variant="destructive" onClick={()=>{setS(F.initialState());setSaveBlocked(false);setReset(false);setReport(false);setMessage('Novo planejamento iniciado.')}}>Apagar e recomeçar</AlertDialogAction></AlertDialogFooter></AlertDialogContent>
  </AlertDialog>
 <a className="account-signout" href="/signout-with-chatgpt?return_to=%2F" target="_top" title={"Sair de "+viewer.email} aria-label={"Sair de "+viewer.email}><LogOut size={14}/><span className="action-label">Sair</span></a>
 </nav>
 <input ref={file} className="sr-only" type="file" accept="application/json,.json" onChange={importFile}/>
 </header><div className={"content-body"+(report?"":" with-context")}><div className="content-scroll" ref={contentScroll} role="region" aria-label="Conteúdo do planejamento" tabIndex={0}><main><div className="eyebrow">{report?'SEU PLANO DE ADOÇÃO':`FASE 0${s.step+1} / 07`}<span>•</span>{report?'VISÃO CONSOLIDADA':F.phaseNames[s.step].toUpperCase()}</div><h1 tabIndex={-1} ref={heading}>{report?'Um caminho claro para começar.':titles[s.step]}</h1><p className="intro">{report?'Leve as decisões para o time e acompanhe a execução com evidências.':descriptions[s.step]}</p>{message&&<div className="notice" role="status"><Info size={16}/><span>{message}</span><Button variant="ghost" size="xs" onClick={()=>setMessage('')}>Fechar</Button></div>}
 <div className={report?'report-area':'work-grid'}><section className="surface">
 {report?<PlanReport {...props}/>:s.step===0?<Diagnostic {...props}/>:s.step===1?<Enablers {...props}/>:s.step===2?<Pilot {...props}/>:s.step===3?<Gaps {...props}/>:s.step===4?<Adoption {...props}/>:s.step===5?<Governance {...props}/>:<Scale {...props}/>}
 {!report&&<>{errors.length>0&&<div className="error-box" role="alert" ref={errorBox} tabIndex={-1}>{errors.map(e=><p key={e}>{e}</p>)}</div>}<div className="card-footer"><Button variant="ghost" disabled={s.step===0&&s.q===-1} onClick={()=>s.step===0?setS(p=>({...p,q:p.q-1})):nav(s.step-1)}><ArrowLeft/> Voltar</Button><Button disabled={!loaded} className="primary-action" onClick={advance}>{s.step===0&&s.q===-1?'Começar diagnóstico':s.step===0&&s.q<8?'Próxima pergunta':s.step===0&&s.q===8?'Ver meu diagnóstico':s.step===6?'Finalizar meu plano':'Revisar e continuar'}<ArrowRight/></Button></div></>}
 </section></div>
 {method&&<section className="surface methodology" id="methodology" ref={methodology} tabIndex={-1}><div className="section-top"><h2>Transparência da adaptação</h2><Button variant="ghost" onClick={()=>setMethod(false)}>Fechar</Button></div><SourceNotes/><p>Fonte: Guia Completo — Framework de Adoção de IA · Tech Leads Club · Beta v0.5, 37 páginas, fornecido por você. Este wizard é uma adaptação independente.</p><ul><li>Diagnóstico: média das 9 dimensões. Baixa &lt; 1,67; média &lt; 2,34; alta ≥ 2,34. Empates de gargalo são decididos por você conforme impacto operacional.</li><li>Piloto: pesos 2, 2, 2, 1, 1; soma dividida por 8.</li><li>Gargalos: a fórmula do guia resulta em 7–21 pontos, embora o texto diga máximo 15. Preservamos a fórmula. O limiar crítico sugerido de 11 pode ser ajustado com justificativa. Marcos por esforço são sugestões desta adaptação.</li><li>Templates: Conservador tem precedência quando não há uso de IA ou a prontidão é baixa. Níveis iniciais por estágio são sugestões editáveis; limites de DX, senioridade, qualidade e CD seguem o guia; a proporção L2+ pode ser calibrada. Autonomia é configurada separadamente.</li><li>O guia tem divergências de pré-requisitos entre cabeçalhos e texto. O planejamento percorre as sete fases e mantém gates explícitos de execução.</li><li>Governança: o texto anuncia 8 políticas, mas lista 9. Escala anuncia 9 métricas, mas lista 11. A v2 separa cinco métricas DORA, resultados e indicadores de adoção. Registros antigos ambíguos são preservados como histórico.</li><li>Metas de ganho são hipóteses a validar, não previsões. Esta aplicação não conecta ferramentas, verifica evidências ou executa mudanças na organização.</li></ul></section>}
 <footer className="bottom-note">Bússola v2 · Base Tech Leads Club + referências 2026 · Adaptação independente</footer>
 </main>{!report&&<aside className="context"><span className="eyebrow">{s.step===0?'O QUE VOCÊ VAI DESCOBRIR':'SEU PLANO EM CONSTRUÇÃO'}</span><h3>{s.step===0?<>Clareza para<br/>dar o próximo passo.</>:s.context.name||'Sua engenharia'}</h3><p>{s.step===0?'Nove dimensões. Três perspectivas sobre a sua engenharia.':`${s.context.size||'—'} pessoas na engenharia · ${done} de 7 fases revisadas.`}</p>{F.groups.map((x,i)=><div className="perspective" key={x}><span>0{i+1}</span>{x}{diag?<strong>{diag.groups[i].toFixed(1).replace('.',',')}</strong>:<ArrowUpRight size={15}/>}</div>)}{diag&&<div className="mini-score"><span>Prontidão {F.readiness[diag.level].toLowerCase()}</span><b>{diag.score.toFixed(2).replace('.',',')}<small> / 3</small></b></div>}<div className="context-note">{s.step===0?'Responda sobre a realidade atual. As respostas vão orientar o plano, sem substituir a avaliação do time.':'As etapas montam o plano. A execução só avança quando os critérios e as evidências forem atendidos.'}</div><Button variant="ghost" className="method-link" onClick={()=>setMethod(!method)}><FileText size={14}/> O que mudou na v2</Button></aside>}</div></div></div></div>
}
