'use client';
import {Check,LockKeyhole} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Progress} from '@/components/ui/progress';
import {Field,Notice,Select} from './wizard-ui';
import * as F from '@/lib/framework.mjs';
export default function Diagnostic({s,setS,group,change}){
 const diag=F.diagnostic(s.answers),answered=Object.keys(s.answers).length;
 if(s.q===-1)return <><div className="section-top"><span className="pill">Seu contexto</span><span className="muted">Antes das 9 perguntas</span></div><h2>Vamos conhecer seu time.</h2><p className="muted">Use o contexto de uma mesma organização em todas as respostas.</p><Field label="Organização ou equipe"><Input placeholder="Ex.: Engenharia de Produto" value={s.context.name} maxLength={160} onChange={e=>group('context','name',e.target.value,0)}/></Field><Field label="Quantas pessoas trabalham na engenharia?"><Input type="number" min={1} max={100000} step={1} placeholder="Ex.: 24" value={s.context.size} onChange={e=>group('context','size',e.target.value,0)}/></Field><Field label="Como a IA é usada hoje?"><Select label="Uso atual de IA" value={s.context.usage} onChange={v=>group('context','usage',v,0)} options={[["none","Ainda não usamos"],["individual","Uso individual"],["team","Padronizada em alguns times"],["organization","Padronizada na organização"]]}/></Field><p className="local-note"><LockKeyhole size={13}/> As respostas ficam neste navegador. Exporte um backup para continuar em outro dispositivo.</p></>;
 if(s.q<9){const d=F.dimensions[s.q];return <><div className="section-top"><span className="pill">{F.groups[Math.floor(s.q/3)]}</span><span className="muted">{s.q+1} de 9 perguntas</span></div><div className="question-progress"><Progress value={answered/9*100} aria-label="Perguntas respondidas"/><span>{answered}/9 respondidas</span></div><div className="question-nav" aria-label="Ir para pergunta">{F.dimensions.map((dim,i)=><button key={dim.key} onClick={()=>setS(p=>({...p,q:i}))} title={dim.name} aria-label={`Questão ${i+1}: ${dim.name}`} aria-current={s.q===i?'step':undefined} className={(s.q===i?'current ':'')+(s.answers[dim.key]?'answered':'')}>{s.answers[dim.key]&&s.q!==i?<Check size={12}/>:i+1}</button>)}</div><h2 className="question-title">{d.question}</h2><fieldset className="choices"><legend className="sr-only">{d.name}</legend>{d.options.map((opt,i)=><label className={'choice '+(s.answers[d.key]===i+1?'selected':'')} key={opt}><input type="radio" name={d.key} value={i+1} checked={s.answers[d.key]===i+1} onChange={()=>change(p=>({...p,answers:{...p.answers,[d.key]:i+1},bottleneck:''}),0)}/><span><b>{['Baixo','Médio','Alto'][i]} <small>{i+1},0 ponto{i?'s':''}</small></b><span>{opt}</span></span></label>)}</fieldset><Notice>{d.impact}</Notice><p className="source-note">Guia, p. {d.page} · Alternativas resumidas, pontuação preservada.</p></>}
 if(!diag)return <Notice>Faltam respostas. <Button variant="ghost" onClick={()=>setS(p=>({...p,q:0}))}>Voltar às perguntas</Button></Notice>;
 return <><div className={'score-banner '+diag.level}><div><span className="eyebrow">PRONTIDÃO DA ENGENHARIA</span><h2>{F.readiness[diag.level]} prontidão</h2><p>{diag.level==='low'?'Fortaleça a base antes de acelerar.':diag.level==='medium'?'Há uma base para começar, com lacunas a resolver.':'Boa base para avançar, preservando qualidade e governança.'}</p></div><strong>{diag.score.toFixed(2).replace('.',',')}<small>/ 3</small></strong></div><div className="dimension-results">{F.dimensions.map((d,i)=><div key={d.key}><span>{d.name}</span><div className="score-dots">{[1,2,3].map(x=><i key={x} className={s.answers[d.key]>=x?'filled':''}/>)}</div><Button variant="ghost" size="xs" onClick={()=>setS(p=>({...p,q:i}))}>Editar</Button></div>)}</div>{diag.lowest.length>1?<Field label="Entre as dimensões empatadas, qual tem maior impacto operacional?" hint="O guia não define uma ordem fixa de desempate. Sua escolha define o gargalo principal."><Select label="Gargalo principal" value={s.bottleneck} onChange={v=>change(p=>({...p,bottleneck:v}),0)} options={[["","Selecione o gargalo principal"],...diag.lowest.map(k=>[k,F.dimensions.find(d=>d.key===k).name])]}/></Field>:<Notice>Gargalo principal: <strong>{F.dimensions.find(d=>d.key===diag.lowest[0]).name}</strong>.</Notice>}<details><summary>Recomendações por dimensão</summary>{F.dimensions.map(d=><p key={d.key}><strong>{d.name}:</strong> {d.actions[s.answers[d.key]-1]}</p>)}</details></>;
}
